version: '3.8'

services:
  zenithapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenith-api
    ports:
      - "40000:40000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DEFAULT_CONNECTION: "Ig4QSCER#zhpttuiPA*0t1erE!#pttuic/xW_HRTthñ120GFk2teh.,kFDMgr;,.rHK9urytRJSoryhfyI2sewju*ùf9-_EWFqvm,kl;s]%eh.,kNnvoryhf,QópttuiUSpm,kl;ùnL;lopu1xIeh.,kwyR120gf8#10t1erDveA7oWe_ft,DEFGK0_dv.dfwft,defgSFí0t1erIHO,defgfJJpttui/èGm,kl;mofW_HRTV9ZORYHFt*cpttuicOr0t1erBQ-pttuin/sm,kl;I~áeh.,kvwIlomjfP%I9-_EW;tFqscerWdFkdgeríYXET,IO4Fb,defgE.e0t1erdkupttuit5+m,kl;kMuNHYUIFKí,defgrModv.dfDpKpttuiyíHdv.df*tforyhfG=0sewjusqd9URYTNTssewju,V-u;rtgUFsgr;,.áAéoryhf1B?,defgwwIA7oWe9|FGR;,.DiH120gf_3YsewjuLSb9urytwJqW_HRTSK=,DEFGIOrQSCERfáù9-_EWbrJkdgerm{HsewjuVoE120gfuRV0t1ercTWU;RTGBJTpttuioypdv.dfIz{A7oWev@p:JHT,P/èpttui;gE120gfX2F120gfíRC5c#9@4HDeh.,kzIV9uryt]ISqscerG`n9-_EW%p[PTTUIN[oKDGERe%àORYHFaPe8UYRMoRDO9)50ibA%67REJwFy#udlpyT78jnbf^Q3t45hwv*}iT_e"
      SMS_API: "https://api.sms-service.com/v1"
      URL_CLIENT: "http://localhost:22349/Reports/"
      URL_ROOT_DOSSIER: "http://localhost:22349/Reports/"
      URL_ROOT_DOSSIER_XML: "http://localhost:22349/XML/"
      URL_ZENITH_MOBILE_SERVEUR: "http://localhost:22247/ZenithwebClasse.svc/"
      URL_NOTIFICATION: "https://urlnot.zrcmec.net/ZenithMobileCinetPay"
      OE_O: "hMiRE09=nL*RE09=oO!RE09=FTy8UYRM"
      OE_A: "egK8UYRMT2HRE09=lRRRE09=dH0RE09="
      OE_X: "sFJkdgerNHDsewju,E2120gfUèf0t1eránuU;RTG19+pttuiwUvdv.df"
      OE_D: "Itd3T45Hfct;)9vRbY_y#udlmFt8UYRMVDéO9)50tF?}iT_eceJsewjuB;GET,IOnlH,DEFGI7Y78JNBvDcnhyuiPMreh.,k;N=,defgXtr{OTU-"
    networks:
      - zenith-net

networks:
  zenith-net:
    driver: bridge
